/**
 * The bundled default page-flip sound, as a base64 `data:` URI.
 *
 * Generated by `scripts/embed-flip-clip.mjs` from `packages/core/assets/flip.mp3` — do not
 * hand-edit. Inlined rather than shipped as a separate asset so the default clip needs no bundler
 * URL resolution and no network fetch (works offline / under strict CSP); consumers who want an
 * external file use the `sound.url` option instead.
 *
 * Empty until a clip is embedded: `FlipSound` then treats `sound: true` (no `url`) as "no default
 * sound" and stays silent, so the feature builds and behaves cleanly before the asset lands.
 */
export const FLIP_CLIP = '';
